services:
  nginx:
    build: 
      context: ./requirements/nginx/.
      dockerfile: Dockerfile
    ports:
      - "8080:443"
        #    volumes:
        #- "$PWD/myvol:/kajuto"
    env_file:
      - ./.env
