services:
  nginx:
    user: root
    build: 
      context: ./requirements/nginx/.
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx_container
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - nwvol:/var/www/html/nginx
    networks:
      - networng
    depends_on: 
      wordpress:
        condition: service_healthy

    restart: always

  wordpress:
    build: 
      context: ./requirements/wordpress/.
      dockerfile: Dockerfile
    image: wordpress
    container_name: wordpress_container
    networks:
      - networng
    env_file:
      - .env
    volumes:
      - nwvol:/var/www/html/wordpress
    ports:
      - "9000:9000"
    depends_on:
      mariadb:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "wp", "core", "is-installed", "--path=/var/www/html/wordpress", "--allow-root"]
      interval: 5s
      timeout: 5s
      retries: 5

  mariadb:
    build:
      context: ./requirements/mariadb/.
      dockerfile: Dockerfile
    image: mariadb
    container_name: mariadb_container
    networks:
      - networng
    env_file:
      - .env
    volumes:
      - mbvol:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  nwvol:
    driver: local
    driver_opts:
      type: none
      device: /home/$USER/data/wordpress
      o: bind
  mbvol:
    driver: local
    driver_opts:
      type: none
      device: /home/$USER/data/mariadb
      o: bind

networks:
  networng:
    ipam:
      config:
        - subnet: 172.18.0.0/24
    driver: "bridge"
   
